version: "3.8"
services:
  app:
    build:
      context: ./backend-java/
    container_name: ssafy_app
    restart: always
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      TZ: "Asia/Seoul"
      JAVA_TOOL_OPTIONS: "-Dkms.url=ws://kurento:8888/kurento"
      server.address: 0.0.0.0
    links:
      - db
    depends_on:
      - db
      - kurento
    networks:
      - backend
  db:
    image: mysql:5.7
    container_name: ssafy_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ssafy_web_db
      MYSQL_ROOT_PASSWORD: ssafy
      MYSQL_USER: ssafy
      MYSQL_PASSWORD: ssafy
      TZ: "Asia/Seoul"
    privileged: true
    platform: linux/x86_64
    networks:
      - backend
  kurento:
    image: kurento/kurento-media-server:latest
    restart: always
    ports:
      - "8888:8888"
    environment:
      TZ: "Asia/Seoul"
      KMS_STUN_IP: "3.34.253.8"
      KMS_STUN_PORT: "3478"
      KMS_TURN_URL: "myuser:mypassword@3.34.253.8:3478?transport=udp"
    platform: linux/x86_64
    networks:
      - backend
networks:
  backend:
